apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer          # Use NodePort if LoadBalancer not supported
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80                # Port exposed externally
      targetPort: 3000        # Port inside the container

