name: CI/CD Pipeline - Build & Deploy to AKS

on:
  push:
    branches: ["main"]

env:
  ACR_NAME: pwimsdevacr
  AKS_RESOURCE_GROUP: myResourceGroup
  AKS_CLUSTER_NAME: my-kaks1
  IMAGE_NAME: myapp

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure CLI - Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
          echo "IMAGE=$ACR_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Push Docker Image
        run: docker push ${{ env.IMAGE }}

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS Credentials
        run: az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/myapp-deployment myapp=${{ env.IMAGE }} --record
          kubectl rollout status deployment/myapp-deployment

